---
driver:
  name: vagrant
  customize:
    memory: 2048
    cpus: 2

provisioner:
  name: chef_zero

platforms:
  - name: centos-5.11
  - name: centos-6.7
  - name: centos-7.1
  - name: ubuntu-10.04
    run_list: apt::default
  - name: ubuntu-12.04
    run_list: apt::default
  - name: ubuntu-14.04
    run_list: apt::default

suites:
  - name: default
    run_list:
      - recipe[test]
      - recipe[test::repo]
    attributes:

  - name: override_package_versions
    run_list:
      - recipe[test]
      - recipe[test::repo]
    attributes:
      test:
        chef-server-core:
          version: 12.0.4-1

  - name: local_package_install
    run_list:
      - recipe[test]
      - recipe[test::local]
    attributes:
