---
driver:
  name: vagrant
  customize:
    memory: 2048
    cpus: 2

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-10.04
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-5.11
  - name: centos-6.6

suites:
  - name: default
    run_list:
      - recipe[test]
      - recipe[chef-server-ingredient]
    attributes:

  - name: override_package_versions
    run_list:
      - recipe[test]
      - recipe[chef-server-ingredient]
    attributes:
      test:
        chef-server-core:
          version: 12.0.4-1
